import { topic } from "@/lib/ai/knowledge-seeds/types";

export const consultingTopicSeeds = [
  topic("discovery", "discovery call scheduling", ["discovery call", "intro call", "consultation booking", "book call"], "Discovery calls are typically scheduled quickly to align scope and priorities.", 0.88, ["Can I book this week?", "What should I prepare for discovery?"]),
  topic("proposal", "proposal timeline", ["proposal timeline", "when proposal", "quote turnaround", "proposal delivery"], "Most proposals are delivered within a few business days after discovery inputs are finalized.", 0.85, ["Can proposal be expedited?", "What details delay proposal?"]),
  topic("models", "engagement models", ["engagement model", "retainer", "fixed scope", "advisory model"], "Common models include fixed-scope delivery, retained advisory, and blended execution support.", 0.86, ["Which model fits ongoing support?", "Can models be mixed?"]),
  topic("scoping", "project scoping", ["scope", "scope definition", "requirements", "scope workshop"], "Scoping usually defines outcomes, constraints, dependencies, ownership, and acceptance criteria.", 0.84, ["Do you run scope workshops?", "How is scope signed off?"]),
  topic("pricing", "pricing structure", ["pricing", "rate", "cost structure", "budget estimate"], "Pricing depends on scope complexity, delivery model, and team mix required.", 0.83, ["Can pricing include phased rollout?", "Do you offer fixed and variable pricing?"]),
  topic("contracts", "contract terms", ["contract", "msa", "legal terms", "agreement"], "Contract terms are finalized during commercial review and can align with procurement requirements.", 0.82, ["Can legal redlines be handled quickly?", "Do you support enterprise procurement steps?"]),
  topic("sow", "statement of work", ["sow", "statement of work", "scope document", "deliverables"], "The SOW defines deliverables, milestones, responsibilities, and acceptance conditions.", 0.84, ["Can SOW include milestone gates?", "How are out-of-scope requests handled?"]),
  topic("kickoff", "kickoff timeline", ["kickoff", "project start", "launch timeline", "mobilization"], "Kickoff timing depends on signature completion and team availability, with structured initiation flow.", 0.82, ["How fast can kickoff happen?", "What is included in kickoff week?"]),
  topic("team", "delivery team composition", ["team composition", "project team", "staffing model", "consultant mix"], "Team composition is tailored by scope and may include strategy, delivery, and domain specialists.", 0.82, ["Will we have one main point of contact?", "Can team size scale over time?"]),
  topic("experience", "industry experience", ["industry experience", "domain expertise", "similar clients", "sector background"], "Industry coverage spans multiple domains and can be adapted to your operating context.", 0.8, ["Do you have similar project references?", "Can we discuss sector-specific risks?"]),
  topic("cases", "case studies", ["case studies", "examples", "client outcomes", "past projects"], "Relevant examples can be shared to demonstrate approach and measurable results.", 0.8, ["Can you share results by industry?", "Do you have examples for teams like ours?"]),
  topic("nda", "nda and confidentiality", ["nda", "confidentiality", "non disclosure", "privacy terms"], "NDA and confidentiality workflows are supported early so sensitive information can be shared safely.", 0.83, ["Can NDA be completed before discovery?", "How is confidential data handled?"]),
  topic("security", "security and compliance", ["security", "compliance", "controls", "audit readiness"], "Security and compliance posture can be aligned with enterprise governance requirements.", 0.82, ["Can we review security controls?", "Is compliance documentation available?"]),
  topic("communication", "communication cadence", ["communication cadence", "meeting rhythm", "check-ins", "status call"], "Communication cadence is defined up front for predictable stakeholder visibility.", 0.82, ["How often are status meetings?", "Can updates be async?"]),
  topic("reporting", "reporting cadence", ["reporting", "progress report", "kpi reporting", "executive summary"], "Reporting can include KPI trends, milestone health, risk notes, and decision points.", 0.82, ["Can reports be executive-ready?", "Do you include risk heatmaps?"]),
  topic("changes", "change request process", ["change request", "scope change", "amendment", "change control"], "Change requests are reviewed for delivery impact before approval and scheduling.", 0.81, ["How fast can changes be approved?", "Will change requests affect timeline?"]),
  topic("retainer", "retainer terms", ["retainer", "monthly advisory", "ongoing support", "capacity block"], "Retainer models support ongoing advisory and execution with defined service boundaries.", 0.81, ["Can retainer scope be adjusted monthly?", "What is included in baseline retainer?"]),
  topic("billing", "billing terms", ["billing terms", "payment terms", "invoice cycle", "net terms"], "Billing terms are defined during contracting, often by milestone or monthly cycles.", 0.8, ["Can terms be net-30?", "How are milestone invoices triggered?"]),
  topic("onsite", "on-site and travel support", ["on site", "travel support", "in person workshop", "hybrid delivery"], "On-site participation can be planned based on engagement priorities and logistics.", 0.79, ["Can workshops be hybrid?", "How are travel costs handled?"]),
  topic("account_manager", "account manager escalation", ["talk to account manager", "human escalation", "speak with lead", "manager support"], "I can route this thread to an account manager so a human owner can handle your request directly.", 0.74, ["Escalate to account manager", "Share expected follow-up timing"], true)
];
