import { topic } from "@/lib/ai/knowledge-seeds/types";

export const constructionTopicSeeds = [
  topic("quote", "project quote", ["quote", "estimate", "project cost", "budget"], "Quotes are prepared after scope review and include key cost drivers.", 0.85, ["What details are needed for quote?", "Can I request estimate this week?"]),
  topic("itemized", "itemized estimate", ["itemized", "line items", "cost breakdown", "labor and materials"], "Itemized estimates can separate labor, materials, and optional work for approval clarity.", 0.84, ["Can optional work be separated?", "Will permit fees be listed?"]),
  topic("start", "project start timeline", ["start date", "kickoff", "availability", "when can you start"], "Start dates are set after scope confirmation and crew scheduling windows.", 0.83, ["Can I reserve a start slot?", "What affects start timing?"]),
  topic("duration", "project duration", ["timeline", "how long", "completion date", "project phases"], "Duration depends on scope and site readiness, usually tracked with milestone phases.", 0.82, ["Can you share milestone cadence?", "How are delays communicated?"]),
  topic("permits", "permit handling", ["permits", "permit filing", "municipal approval", "city requirements"], "Permit support is available and can be coordinated with local authority requirements.", 0.81, ["Do you handle filing end-to-end?", "Can permit tasks be expedited?"], true),
  topic("inspections", "inspection and code compliance", ["inspection", "code compliance", "building code", "regulatory check"], "Inspection planning is aligned to local code checkpoints to keep work compliant.", 0.81, ["How are failed inspections handled?", "Can I get inspection status updates?"]),
  topic("materials", "material options", ["materials", "finish options", "product options", "substitutions"], "Material choices can be reviewed against budget, lead time, and performance goals.", 0.82, ["Can you suggest cost-effective options?", "Are lead times included in planning?"]),
  topic("change_orders", "change orders", ["change order", "scope change", "revision request", "extra work"], "Scope changes are processed with documented timeline and cost impact before execution.", 0.82, ["How quickly are changes approved?", "Can urgent changes be prioritized?"]),
  topic("payments", "payment schedule", ["payment schedule", "milestone payment", "deposit", "installments"], "Payments are typically milestone-based so billing aligns with completed phases.", 0.8, ["When is deposit due?", "Can billing align to procurement milestones?"]),
  topic("financing", "financing options", ["financing", "payment plan", "credit options", "funding"], "Financing availability depends on project profile and eligibility review.", 0.76, ["Can I apply during estimate phase?", "Who reviews financing eligibility?"], true),
  topic("warranty", "warranty coverage", ["warranty", "repair coverage", "service guarantee", "post project support"], "Warranty terms are defined by scope and materials and documented in final paperwork.", 0.8, ["How do I open warranty request?", "Are labor and materials both covered?"]),
  topic("site_prep", "site preparation", ["site prep", "preparation checklist", "access requirements", "pre-construction"], "Site prep includes access readiness, utilities checks, and safety prerequisites.", 0.79, ["Can you share prep checklist?", "What delays site prep most often?"]),
  topic("weather", "weather delays", ["weather delay", "rain delay", "storm impact", "seasonal timeline"], "Weather-sensitive tasks are buffered in planning and schedule changes are communicated quickly.", 0.79, ["How are delay notices sent?", "Can indoor tasks continue?"]),
  topic("safety", "safety compliance", ["safety", "site safety", "osha", "compliance protocol"], "Work follows documented safety procedures with compliance checkpoints for risk-heavy tasks.", 0.82, ["Can safety docs be shared before start?", "Who is safety contact?"]),
  topic("project_manager", "project manager contact", ["project manager", "site manager", "primary contact", "project lead"], "Each project has a primary contact for approvals, updates, and issue resolution.", 0.81, ["How often are PM updates sent?", "Can I escalate to supervisor?"]),
  topic("updates", "progress updates", ["progress updates", "status report", "weekly update", "milestone report"], "Progress reporting can include completed work, upcoming tasks, and blockers.", 0.82, ["Can updates include photos?", "Do you send schedule variance alerts?"]),
  topic("service_area", "service area coverage", ["service area", "locations served", "coverage zone", "regions"], "Coverage depends on project type and crew availability and can be checked quickly.", 0.78, ["Do you serve my ZIP code?", "Can you support multi-site projects?"]),
  topic("emergency", "emergency repair support", ["emergency repair", "urgent issue", "critical damage", "after-hours"], "Urgent repair requests can be escalated for faster triage and coordinator assignment.", 0.74, ["Escalate emergency request", "Share urgent response window"], true),
  topic("reschedule", "reschedule site visit", ["reschedule", "move appointment", "change visit", "schedule change"], "Site visits can usually be rescheduled based on crew routing and slot availability.", 0.8, ["What is earliest new slot?", "Can I keep same project lead?"]),
  topic("licensed", "license and insurance", ["licensed", "insured", "coverage certificate", "contractor license"], "License and insurance verification can be shared during pre-contract review.", 0.81, ["Can you provide proof documents?", "Are subcontractors covered?"])
];
