import { topic } from "@/lib/ai/knowledge-seeds/types";

export const dentalTopicSeeds = [
  topic("booking", "book appointment", ["book appointment", "schedule visit", "reserve slot", "new patient booking"], "Appointments can be scheduled by visit type and available provider slots.", 0.86, ["What is earliest available slot?", "Can I choose a specific dentist?"]),
  topic("reschedule", "reschedule or cancel appointment", ["reschedule", "cancel appointment", "change booking", "move my visit"], "Appointment changes are supported with updated confirmation details.", 0.84, ["Can I reschedule online?", "Is there a cancellation window?"]),
  topic("walkins", "walk in policy", ["walk in", "same day visit", "no appointment", "urgent slot"], "Walk-in availability depends on same-day capacity, with urgent cases triaged first.", 0.79, ["Do you have same-day openings?", "Can urgent pain cases be prioritized?"], true),
  topic("insurance", "accepted insurance providers", ["insurance accepted", "providers", "ppo", "network coverage"], "Most major PPO plans are supported and network status can be verified.", 0.88, ["Can you check my insurance carrier?", "Do you accept out-of-network plans?"]),
  topic("verify", "insurance verification", ["coverage verification", "benefits check", "eligibility", "insurance precheck"], "Coverage verification can be completed before treatment to clarify expected benefits.", 0.85, ["Can you verify before appointment?", "Will I get estimate after verification?"]),
  topic("payments", "payment options", ["payment options", "card", "payment plan", "financing"], "Payment options include standard methods and financing paths for eligible cases.", 0.79, ["Can I pay in installments?", "Do you accept contactless payments?"]),
  topic("estimate", "treatment estimate", ["treatment estimate", "procedure cost", "pricing", "expected cost"], "Treatment estimates are prepared after clinical assessment and insurance review.", 0.82, ["Can I get estimate before treatment?", "Will insurance contribution be included?"]),
  topic("emergency", "dental emergency", ["emergency", "severe pain", "tooth trauma", "urgent care"], "Urgent dental concerns can be escalated for priority clinical triage.", 0.76, ["Escalate to urgent care team", "What should I do right now?"], true),
  topic("pediatric", "pediatric care", ["kids dentist", "child appointment", "pediatric", "children care"], "Pediatric appointments are available with age-appropriate care guidance.", 0.8, ["Do you support first-visit guidance for kids?", "Can siblings be scheduled together?"]),
  topic("ortho", "orthodontic services", ["orthodontics", "braces", "aligners", "teeth alignment"], "Orthodontic consultation availability depends on provider schedule and treatment plan.", 0.8, ["Do you offer aligner plans?", "How do I book orthodontic consult?"]),
  topic("cleaning", "cleaning frequency", ["cleaning schedule", "how often cleaning", "preventive visit", "checkup frequency"], "Cleaning cadence is usually based on oral health profile and provider recommendations.", 0.83, ["Should I schedule every 6 months?", "Can high-risk patients come more often?"]),
  topic("aftercare", "aftercare instructions", ["aftercare", "post treatment care", "recovery instructions", "home care"], "Aftercare guidance is provided per procedure and includes warning signs for follow-up.", 0.84, ["Can you repeat aftercare steps?", "When should I call clinic?"]),
  topic("pain", "post treatment pain", ["pain after treatment", "soreness", "discomfort", "swelling"], "Mild discomfort may be expected, but worsening pain should be reviewed promptly.", 0.78, ["Is this pain level expected?", "Can I escalate to clinician review?"], true),
  topic("prescription", "prescription refill", ["prescription refill", "medication refill", "rx request", "pharmacy"], "Prescription requests are reviewed under clinical policy with urgency flags when needed.", 0.75, ["How long do refill approvals take?", "Can this be reviewed urgently?"], true),
  topic("records", "xray and records requests", ["xray records", "dental records", "records transfer", "imaging request"], "Records transfers can be processed with patient verification and clinic routing.", 0.8, ["How do I request records transfer?", "Can records be sent to another clinic?"]),
  topic("forms", "medical forms", ["forms", "medical history", "intake paperwork", "consent forms"], "Patient forms can be completed before arrival to reduce check-in friction.", 0.81, ["Can I complete forms online?", "What documents should I bring?"]),
  topic("reminders", "appointment reminders", ["reminders", "notification", "text reminder", "email reminder"], "Reminders are sent ahead of visits with confirmation instructions.", 0.82, ["Can I get SMS reminders?", "How do I confirm quickly?"]),
  topic("wait", "wait times", ["wait time", "clinic delay", "running late", "waiting room"], "Wait times vary by daily load and urgent triage priorities.", 0.77, ["Can you check current delay?", "Can late appointments be rescheduled?"]),
  topic("sedation", "sedation options", ["sedation", "anxiety support", "comfort options", "nitrous"], "Sedation availability depends on treatment type and clinical suitability.", 0.78, ["How do I know if sedation is eligible?", "Can I discuss sedation before booking?"]),
  topic("frontdesk", "front desk escalation", ["front desk", "talk to staff", "human support", "live person"], "I can route this to front desk support for direct human assistance.", 0.74, ["Escalate to front desk", "Share callback window"], true)
];
