import { topic } from "@/lib/ai/knowledge-seeds/types";

export const ecommerceTopicSeeds = [
  topic("tracking", "order tracking", ["where is my order", "track order", "shipment status", "delivery status"], "Order tracking reflects carrier scan events and estimated delivery updates.", 0.88, ["Tracking has not updated, what now?", "Can you check delivery ETA?"]),
  topic("edit_order", "order edit window", ["edit order", "change order", "update address", "modify purchase"], "Order edits are typically possible shortly after checkout before fulfillment lock.", 0.83, ["How long is edit window?", "Can I change shipping address now?"]),
  topic("cancel_order", "order cancellation", ["cancel order", "stop shipment", "void purchase", "cancel before ship"], "Cancellation eligibility depends on fulfillment stage and dispatch timing.", 0.81, ["Can this be canceled immediately?", "What if order already shipped?"]),
  topic("returns", "return policy", ["return policy", "return item", "send back", "return window"], "Returns are accepted within policy windows when item condition requirements are met.", 0.86, ["How do I start a return?", "Are final-sale items returnable?"]),
  topic("refunds", "refund timing", ["refund timing", "refund status", "money back timeline", "refund processing"], "Refunds are processed after return validation and bank settlement time may vary.", 0.84, ["Can you check refund status?", "Why is refund still pending?"]),
  topic("exchange", "exchange policy", ["exchange", "swap size", "replace item", "exchange process"], "Exchanges are supported when replacement stock is available and return validation passes.", 0.81, ["Can I exchange for different size?", "How long does exchange take?"]),
  topic("shipping", "shipping options", ["shipping methods", "express shipping", "delivery speed", "shipping cost"], "Shipping options vary by destination and fulfillment center availability.", 0.82, ["Do you offer next-day shipping?", "How is shipping fee calculated?"]),
  topic("international", "international shipping", ["international shipping", "ship abroad", "global delivery", "overseas order"], "International shipping depends on country rules, carrier coverage, and product restrictions.", 0.8, ["Do you ship to my country?", "How long does international delivery take?"]),
  topic("customs", "customs duties", ["customs", "import duty", "international fees", "border charges"], "Customs duties and local taxes may apply depending on destination import policy.", 0.79, ["Can duties be prepaid?", "Who pays customs on delivery?"]),
  topic("lost", "lost package", ["lost package", "missing order", "not delivered", "shipment missing"], "Missing packages can be escalated for carrier trace and fulfillment investigation.", 0.74, ["Escalate to fulfillment", "Open lost package claim"], true),
  topic("damaged", "damaged item", ["damaged item", "arrived broken", "shipping damage", "defective on arrival"], "Damage reports are reviewed with order evidence for replacement or refund resolution.", 0.78, ["How do I submit damage photos?", "Can this be replaced urgently?"], true),
  topic("wrong_item", "wrong item received", ["wrong item", "incorrect order", "received different product", "packing error"], "Wrong-item issues can be resolved through replacement workflow and return label support.", 0.8, ["Can correct item ship first?", "How do I return incorrect item?"]),
  topic("size", "size and fit guide", ["size guide", "fit help", "measurement chart", "which size"], "Sizing support uses product charts and fit notes to reduce exchange risk.", 0.79, ["Where can I see measurement chart?", "Can support recommend size?"]),
  topic("warranty", "product warranty", ["warranty", "coverage period", "warranty claim", "repair coverage"], "Warranty terms vary by product category and require order verification for claims.", 0.79, ["How do I submit warranty claim?", "What does warranty include?"]),
  topic("payments", "payment methods", ["payment method", "credit card", "wallet", "checkout payment"], "Checkout supports standard online payment methods depending on region and order type.", 0.8, ["Why did payment fail?", "Can I change payment method later?"]),
  topic("promo", "promo code support", ["promo code", "discount code", "coupon", "offer code"], "Promo eligibility depends on campaign rules such as timing, SKU scope, and spend threshold.", 0.78, ["Why is code not applying?", "Can codes be combined?"]),
  topic("gift_card", "gift card support", ["gift card", "gift balance", "redeem card", "gift voucher"], "Gift cards can be redeemed at checkout and balances follow gift-credit policy.", 0.79, ["How do I check gift card balance?", "Can gift cards expire?"]),
  topic("subscription", "subscription orders", ["subscription order", "recurring order", "pause subscription", "skip shipment"], "Subscription orders can usually be paused, skipped, or updated before next cycle.", 0.8, ["Can I skip next shipment?", "How do I pause subscription?"]),
  topic("login", "account login help", ["login help", "password reset", "cannot sign in", "locked account"], "Account access issues can be handled through secure reset and verification flow.", 0.8, ["How do I reset password?", "Can support unlock account?"]),
  topic("fraud", "fraud review", ["fraud check", "payment hold", "order under review", "risk verification"], "Risk-reviewed orders may need additional verification before release to fulfillment.", 0.74, ["Escalate fraud review", "What verification is needed?"], true)
];
